/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeExecutionIdRouteImport } from './routes/resume.$executionId'
import { Route as IntegrationsNamespaceRouteImport } from './routes/integrations.$namespace'
import { Route as PluginsPluginIdSplatRouteImport } from './routes/plugins.$pluginId.$'
import { Route as IntegrationsAddPluginKeyRouteImport } from './routes/integrations.add.$pluginKey'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeExecutionIdRoute = ResumeExecutionIdRouteImport.update({
  id: '/resume/$executionId',
  path: '/resume/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsNamespaceRoute = IntegrationsNamespaceRouteImport.update({
  id: '/integrations/$namespace',
  path: '/integrations/$namespace',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdSplatRoute = PluginsPluginIdSplatRouteImport.update({
  id: '/plugins/$pluginId/$',
  path: '/plugins/$pluginId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsAddPluginKeyRoute =
  IntegrationsAddPluginKeyRouteImport.update({
    id: '/integrations/add/$pluginKey',
    path: '/integrations/add/$pluginKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof ToolsRoute
  '/integrations/$namespace': typeof IntegrationsNamespaceRoute
  '/resume/$executionId': typeof ResumeExecutionIdRoute
  '/integrations/add/$pluginKey': typeof IntegrationsAddPluginKeyRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof ToolsRoute
  '/integrations/$namespace': typeof IntegrationsNamespaceRoute
  '/resume/$executionId': typeof ResumeExecutionIdRoute
  '/integrations/add/$pluginKey': typeof IntegrationsAddPluginKeyRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof ToolsRoute
  '/integrations/$namespace': typeof IntegrationsNamespaceRoute
  '/resume/$executionId': typeof ResumeExecutionIdRoute
  '/integrations/add/$pluginKey': typeof IntegrationsAddPluginKeyRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/policies'
    | '/secrets'
    | '/tools'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
    | '/plugins/$pluginId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/policies'
    | '/secrets'
    | '/tools'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
    | '/plugins/$pluginId/$'
  id:
    | '__root__'
    | '/'
    | '/policies'
    | '/secrets'
    | '/tools'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
    | '/plugins/$pluginId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliciesRoute: typeof PoliciesRoute
  SecretsRoute: typeof SecretsRoute
  ToolsRoute: typeof ToolsRoute
  IntegrationsNamespaceRoute: typeof IntegrationsNamespaceRoute
  ResumeExecutionIdRoute: typeof ResumeExecutionIdRoute
  IntegrationsAddPluginKeyRoute: typeof IntegrationsAddPluginKeyRoute
  PluginsPluginIdSplatRoute: typeof PluginsPluginIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$executionId': {
      id: '/resume/$executionId'
      path: '/resume/$executionId'
      fullPath: '/resume/$executionId'
      preLoaderRoute: typeof ResumeExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$namespace': {
      id: '/integrations/$namespace'
      path: '/integrations/$namespace'
      fullPath: '/integrations/$namespace'
      preLoaderRoute: typeof IntegrationsNamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/$': {
      id: '/plugins/$pluginId/$'
      path: '/plugins/$pluginId/$'
      fullPath: '/plugins/$pluginId/$'
      preLoaderRoute: typeof PluginsPluginIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/add/$pluginKey': {
      id: '/integrations/add/$pluginKey'
      path: '/integrations/add/$pluginKey'
      fullPath: '/integrations/add/$pluginKey'
      preLoaderRoute: typeof IntegrationsAddPluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliciesRoute: PoliciesRoute,
  SecretsRoute: SecretsRoute,
  ToolsRoute: ToolsRoute,
  IntegrationsNamespaceRoute: IntegrationsNamespaceRoute,
  ResumeExecutionIdRoute: ResumeExecutionIdRoute,
  IntegrationsAddPluginKeyRoute: IntegrationsAddPluginKeyRoute,
  PluginsPluginIdSplatRoute: PluginsPluginIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
