/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesNamespaceRouteImport } from './routes/sources.$namespace'
import { Route as ResumeExecutionIdRouteImport } from './routes/resume.$executionId'
import { Route as SourcesAddPluginKeyRouteImport } from './routes/sources.add.$pluginKey'
import { Route as PluginsPluginIdSplatRouteImport } from './routes/plugins.$pluginId.$'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesNamespaceRoute = SourcesNamespaceRouteImport.update({
  id: '/sources/$namespace',
  path: '/sources/$namespace',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeExecutionIdRoute = ResumeExecutionIdRouteImport.update({
  id: '/resume/$executionId',
  path: '/resume/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesAddPluginKeyRoute = SourcesAddPluginKeyRouteImport.update({
  id: '/sources/add/$pluginKey',
  path: '/sources/add/$pluginKey',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdSplatRoute = PluginsPluginIdSplatRouteImport.update({
  id: '/plugins/$pluginId/$',
  path: '/plugins/$pluginId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof ToolsRoute
  '/resume/$executionId': typeof ResumeExecutionIdRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof ToolsRoute
  '/resume/$executionId': typeof ResumeExecutionIdRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof ToolsRoute
  '/resume/$executionId': typeof ResumeExecutionIdRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/policies'
    | '/secrets'
    | '/tools'
    | '/resume/$executionId'
    | '/sources/$namespace'
    | '/plugins/$pluginId/$'
    | '/sources/add/$pluginKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/policies'
    | '/secrets'
    | '/tools'
    | '/resume/$executionId'
    | '/sources/$namespace'
    | '/plugins/$pluginId/$'
    | '/sources/add/$pluginKey'
  id:
    | '__root__'
    | '/'
    | '/policies'
    | '/secrets'
    | '/tools'
    | '/resume/$executionId'
    | '/sources/$namespace'
    | '/plugins/$pluginId/$'
    | '/sources/add/$pluginKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliciesRoute: typeof PoliciesRoute
  SecretsRoute: typeof SecretsRoute
  ToolsRoute: typeof ToolsRoute
  ResumeExecutionIdRoute: typeof ResumeExecutionIdRoute
  SourcesNamespaceRoute: typeof SourcesNamespaceRoute
  PluginsPluginIdSplatRoute: typeof PluginsPluginIdSplatRoute
  SourcesAddPluginKeyRoute: typeof SourcesAddPluginKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$namespace': {
      id: '/sources/$namespace'
      path: '/sources/$namespace'
      fullPath: '/sources/$namespace'
      preLoaderRoute: typeof SourcesNamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$executionId': {
      id: '/resume/$executionId'
      path: '/resume/$executionId'
      fullPath: '/resume/$executionId'
      preLoaderRoute: typeof ResumeExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/add/$pluginKey': {
      id: '/sources/add/$pluginKey'
      path: '/sources/add/$pluginKey'
      fullPath: '/sources/add/$pluginKey'
      preLoaderRoute: typeof SourcesAddPluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/$': {
      id: '/plugins/$pluginId/$'
      path: '/plugins/$pluginId/$'
      fullPath: '/plugins/$pluginId/$'
      preLoaderRoute: typeof PluginsPluginIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliciesRoute: PoliciesRoute,
  SecretsRoute: SecretsRoute,
  ToolsRoute: ToolsRoute,
  ResumeExecutionIdRoute: ResumeExecutionIdRoute,
  SourcesNamespaceRoute: SourcesNamespaceRoute,
  PluginsPluginIdSplatRoute: PluginsPluginIdSplatRoute,
  SourcesAddPluginKeyRoute: SourcesAddPluginKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
