/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SetupMcpRouteImport } from './routes/setup-mcp'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OrgRouteImport } from './routes/org'
import { Route as OauthAppsRouteImport } from './routes/oauth-apps'
import { Route as CreateOrgRouteImport } from './routes/create-org'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeExecutionIdRouteImport } from './routes/resume.$executionId'
import { Route as IntegrationsNamespaceRouteImport } from './routes/integrations.$namespace'
import { Route as BillingPlansRouteImport } from './routes/billing_.plans'
import { Route as IntegrationsAddPluginKeyRouteImport } from './routes/integrations.add.$pluginKey'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupMcpRoute = SetupMcpRouteImport.update({
  id: '/setup-mcp',
  path: '/setup-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAppsRoute = OauthAppsRouteImport.update({
  id: '/oauth-apps',
  path: '/oauth-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrgRoute = CreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeExecutionIdRoute = ResumeExecutionIdRouteImport.update({
  id: '/resume/$executionId',
  path: '/resume/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsNamespaceRoute = IntegrationsNamespaceRouteImport.update({
  id: '/integrations/$namespace',
  path: '/integrations/$namespace',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPlansRoute = BillingPlansRouteImport.update({
  id: '/billing_/plans',
  path: '/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsAddPluginKeyRoute =
  IntegrationsAddPluginKeyRouteImport.update({
    id: '/integrations/add/$pluginKey',
    path: '/integrations/add/$pluginKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/create-org': typeof CreateOrgRoute
  '/oauth-apps': typeof OauthAppsRoute
  '/org': typeof OrgRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/tools': typeof ToolsRoute
  '/billing/plans': typeof BillingPlansRoute
  '/integrations/$namespace': typeof IntegrationsNamespaceRoute
  '/resume/$executionId': typeof ResumeExecutionIdRoute
  '/integrations/add/$pluginKey': typeof IntegrationsAddPluginKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/create-org': typeof CreateOrgRoute
  '/oauth-apps': typeof OauthAppsRoute
  '/org': typeof OrgRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/tools': typeof ToolsRoute
  '/billing/plans': typeof BillingPlansRoute
  '/integrations/$namespace': typeof IntegrationsNamespaceRoute
  '/resume/$executionId': typeof ResumeExecutionIdRoute
  '/integrations/add/$pluginKey': typeof IntegrationsAddPluginKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/create-org': typeof CreateOrgRoute
  '/oauth-apps': typeof OauthAppsRoute
  '/org': typeof OrgRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/tools': typeof ToolsRoute
  '/billing_/plans': typeof BillingPlansRoute
  '/integrations/$namespace': typeof IntegrationsNamespaceRoute
  '/resume/$executionId': typeof ResumeExecutionIdRoute
  '/integrations/add/$pluginKey': typeof IntegrationsAddPluginKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/billing'
    | '/create-org'
    | '/oauth-apps'
    | '/org'
    | '/policies'
    | '/secrets'
    | '/setup-mcp'
    | '/tools'
    | '/billing/plans'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/billing'
    | '/create-org'
    | '/oauth-apps'
    | '/org'
    | '/policies'
    | '/secrets'
    | '/setup-mcp'
    | '/tools'
    | '/billing/plans'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/billing'
    | '/create-org'
    | '/oauth-apps'
    | '/org'
    | '/policies'
    | '/secrets'
    | '/setup-mcp'
    | '/tools'
    | '/billing_/plans'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BillingRoute: typeof BillingRoute
  CreateOrgRoute: typeof CreateOrgRoute
  OauthAppsRoute: typeof OauthAppsRoute
  OrgRoute: typeof OrgRoute
  PoliciesRoute: typeof PoliciesRoute
  SecretsRoute: typeof SecretsRoute
  SetupMcpRoute: typeof SetupMcpRoute
  ToolsRoute: typeof ToolsRoute
  BillingPlansRoute: typeof BillingPlansRoute
  IntegrationsNamespaceRoute: typeof IntegrationsNamespaceRoute
  ResumeExecutionIdRoute: typeof ResumeExecutionIdRoute
  IntegrationsAddPluginKeyRoute: typeof IntegrationsAddPluginKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-mcp': {
      id: '/setup-mcp'
      path: '/setup-mcp'
      fullPath: '/setup-mcp'
      preLoaderRoute: typeof SetupMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-apps': {
      id: '/oauth-apps'
      path: '/oauth-apps'
      fullPath: '/oauth-apps'
      preLoaderRoute: typeof OauthAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$executionId': {
      id: '/resume/$executionId'
      path: '/resume/$executionId'
      fullPath: '/resume/$executionId'
      preLoaderRoute: typeof ResumeExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$namespace': {
      id: '/integrations/$namespace'
      path: '/integrations/$namespace'
      fullPath: '/integrations/$namespace'
      preLoaderRoute: typeof IntegrationsNamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing_/plans': {
      id: '/billing_/plans'
      path: '/billing/plans'
      fullPath: '/billing/plans'
      preLoaderRoute: typeof BillingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/add/$pluginKey': {
      id: '/integrations/add/$pluginKey'
      path: '/integrations/add/$pluginKey'
      fullPath: '/integrations/add/$pluginKey'
      preLoaderRoute: typeof IntegrationsAddPluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  BillingRoute: BillingRoute,
  CreateOrgRoute: CreateOrgRoute,
  OauthAppsRoute: OauthAppsRoute,
  OrgRoute: OrgRoute,
  PoliciesRoute: PoliciesRoute,
  SecretsRoute: SecretsRoute,
  SetupMcpRoute: SetupMcpRoute,
  ToolsRoute: ToolsRoute,
  BillingPlansRoute: BillingPlansRoute,
  IntegrationsNamespaceRoute: IntegrationsNamespaceRoute,
  ResumeExecutionIdRoute: ResumeExecutionIdRoute,
  IntegrationsAddPluginKeyRoute: IntegrationsAddPluginKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
